include:
  - local: 'src/virtio/ci/gitlab-ci-inc.yml'

venus-lavapipe:
  extends:
    - .deqp-test
    - .venus-lavapipe-test
  variables:
    DEQP_FRACTION: 60
    DEQP_SUITE: venus
    GPU_VERSION: venus
    LP_NUM_THREADS: 2
    CROSVM_MEMORY: 12288
    CROSVM_CPU: $FDO_CI_CONCURRENT
    FLAKES_CHANNEL: "#virgl-ci"
  script:
    - ./install/crosvm-runner.sh ./install/deqp-runner.sh
